# Use a imagem base do Node.js
FROM node:16 AS build

# Defina o diretório de trabalho dentro do container
WORKDIR /app

# Copie apenas os arquivos package*.json (evita copiar arquivos desnecessários inicialmente)
COPY package*.json ./

# Instale as dependências do projeto
RUN npm install

# Copie o restante do código fonte (após instalar as dependências para aproveitar o cache do Docker)
COPY . .

# Instale o pacote @types/node para fornecer definições de tipo para o Node.js
RUN npm install --save-dev @types/node

# Instale as dependências de tipos do express, body-parser, cors, dotenv
RUN npm install --save-dev @types/express @types/body-parser @types/cors @types/dotenv
RUN npm install express body-parser cors dotenv
RUN npm install --save-dev @types/express @types/body-parser @types/cors @types/dotenv typescript ts-node
RUN npm install axios
RUN npm install --save-dev @types/axios




# Instale o nodemon e ts-node globalmente
RUN npm install -g nodemon ts-node

# Construa o projeto (caso tenha etapas de build)
RUN npm run build

# Exponha a porta do seu backend
EXPOSE 8080

# Defina o comando para iniciar o servidor com nodemon e ts-node
CMD ["npm", "start"]
