# Use a imagem base do Node.js
FROM node:16 AS build

# Defina o diretório de trabalho dentro do container
WORKDIR /app

# Copie os arquivos de configuração do npm
COPY package*.json ./

# Instale as dependências do projeto
RUN npm install

# Instale o pacote @types/node para fornecer definições de tipo para o Node.js
RUN npm install --save-dev @types/node

# Instale as dependências de tipos do express, body-parser, cors, dotenv
RUN npm install --save-dev @types/express @types/body-parser @types/cors @types/dotenv

# Instale o nodemon e ts-node globalmente
RUN npm install -g nodemon ts-node

# Copie o restante do código fonte
COPY . .

# Construa o projeto (caso tenha etapas de build)
RUN npm run build

# Defina o diretório de trabalho para a execução
WORKDIR /app

# Exponha a porta do seu backend
EXPOSE 8080

# Use o nodemon para rodar o servidor com ts-node
CMD ["npm", "start"]
